import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import axios from "axios";
import { useState, useEffect } from "react";

export const Container = styled.div`
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 80px calc(100vh - 80px);
  grid-template-areas:
    "header"
    "main";
  background-color: #373b3e;
  color: white;
`;

export const Header = styled.div`
  grid-area: header;
  background-color: #004480;
  border-bottom: 1px solid rgba(0, 0, 0, 0.2);

  display: flex;
  align-items: center;
  justify-content: center;

  input {
    outline: none;
    padding: 10px;
    font-size: 20px;
  }
`;

export const Main = styled.div`
  grid-area: main;

  margin-top: 20px;
  font-size: 23px;
  font-family: "Anonymous Pro", monospace, "Courier New", Courier;

  display: flex;
  justify-content: center;
`;

export async function getServerSideProps(context) {
  // const data = await axios({
  //   method: "post",
  //   url: "http://localhost:5002/",
  //   data: {
  //     firstName: "Finn",
  //     lastName: "Williams",
  //   },
  // });

  const { data } = await axios({
    method: "get",
    url: "http://localhost:5002/",
  });

  return {
    props: {
      data: data,
    },
  };
}

export default function Home(data) {
  const [items, setItems] = useState([]);
  const [value, setValue] = useState("");

  useEffect(() => {
    const done = async () => {
      setItems(data.data);
    };
    done();
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault();
    console.log(value);
    setValue("");
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <form onSubmit={(e) => handleSubmit(e)}>
          <input
            type="text"
            placeholder="Pesquise uma frase.."
            value={value}
            onChange={(e) => {
              setValue(e.currentTarget.value);
            }}
          />
        </form>
      </Header>
      <Main>
        {items.map((item, key) => {
          return (
            <div key={key}>
              <p style={{ marginBottom: "5px" }}> - {item.word}</p>
              <div>
                <span style={{ fontStyle: "italic", fontSize: "20px" }}>
                  {item.meaning}
                </span>
              </div>
            </div>
          );
        })}
      </Main>
    </Container>
  );
}
