import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import styled from "styled-components";
import axios from "axios";
import { useState, useEffect } from "react";

export const Container = styled.div`
  display: grid;
  grid-template-columns: 1fr;
  grid-template-rows: 80px calc(100vh - 80px);
  grid-template-areas:
    "header"
    "main";
  /* background-color: rgb(239, 141, 21); */
  /* background-color: #373b3e; */
  /* background: linear-gradient(rgba(200, 0, 200), rgba(100, 0, 200)); */
  /* background: linear-gradient(1li00deg, rgba(200, 0, 200), rgb(239, 141, 21)); */
  color: white;
`;

export const Header = styled.div`
  grid-area: header;
  background-color: #004480;
  border-bottom: 1px solid rgba(0, 0, 0, 0.2);

  display: flex;
  align-items: center;
  /* justify-content: space-between; */

  input {
    outline: none;
    padding: 10px;
    font-size: 20px;
  }
`;

export const Main = styled.div`
  grid-area: main;

  margin-top: 20px;
  font-size: 23px;
  font-family: "Anonymous Pro", monospace, "Courier New", Courier;

  display: flex;
  /* flex-wrap: wrap; */
  flex-direction: column;
  align-items: center;

  padding: 20px;
  text-shadow: 2px 2px rgba(0, 0, 0, 0.311);
  /* box-shadow: 2px 2px rgba(0, 0, 0); */
  /* justify-content: center; */
`;

export const PanelLogo = styled.h1`
  width: 200px;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  margin-left: 50px;
`;

export const getServerSideProps = async (ctx) => {
  return {
    props: [],
  };
};

export default function Home() {
  const [items, setItems] = useState([]);
  const [value, setValue] = useState("");

  useEffect(() => {
    setItems([]);
    const done = async () => {
      const { data } = await axios({
        method: "get",
        url: "https://api-gaules.herokuapp.com/",
      });

      // console.log(data);
      setItems(data);
    };
    done();
  }, []);

  useEffect(() => {
    setTimeout(() => {
      if (!value) {
        const done = async () => {
          const { data } = await axios({
            method: "get",
            url: "https://api-gaules.herokuapp.com/",
            // url: "http://localhost:5002/",
          });

          setItems(data);
        };
        done();
      }
    }, 200);
  }, [value]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setValue("");
  };

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <PanelLogo>
          <Image
            src={"/helmet.png"}
            width={100}
            height={100}
            alt={"Gaules Capacete"}
          ></Image>
          <div style={{ marginLeft: "20px", width: "100px" }}>Gaulês Verso</div>
        </PanelLogo>
        <form onSubmit={(e) => handleSubmit(e)} style={{ margin: "auto" }}>
          <input
            type="text"
            placeholder="Pesquise uma frase.."
            value={value}
            onChange={async (e) => {
              setValue(e.currentTarget.value);

              await axios({
                method: "get",
                url: `http://localhost:5002/${e.currentTarget.value}`,
              })
                .then((result) => {
                  setItems(result.data);
                })
                .catch((err) => {
                  setItems(err);
                });
            }}
          />
        </form>
      </Header>
      <Main>
        {items && items ? (
          Object.keys(items).map((item, key) => {
            return (
              <div key={key}>
                <div>{items[item].word}</div>
                <div>{items[item].meaning}</div>
                <br></br>
                <br></br>
              </div>
            );
          })
        ) : (
          <div>nothing..</div>
        )}
      </Main>
    </Container>
  );
}
